NO_OF_DAYS_BEFORE_TO_NOTIFY = 10
DATE_FORMAT = "%d-%m-%Y"
START_SUBSCRIPTION = "START_SUBSCRIPTION"
ADD_SUBSCRIPTION = "ADD_SUBSCRIPTION"
ADD_TOPUP = "ADD_TOPUP"
PRINT_RENEWAL_DETAILS = "PRINT_RENEWAL_DETAILS"
INPUT_ZERO = 0
