# constants used in overall application
ZERO = 0
ONE = 1
TWO = 2
THREE = 3
INPUT_ZERO = 0
INPUT_ONE = 1
INPUT_TWO = 2
TOPUP_COST_ZERO = 0
NO_OF_DAYS_BEFORE_TO_NOTIFY = 10
DATE_FORMAT = "%d-%m-%Y"
ADD_TOPUP = "ADD_TOPUP"
ADD_SUBSCRIPTION = "ADD_SUBSCRIPTION"
START_SUBSCRIPTION = "START_SUBSCRIPTION"
RENEWAL_AMOUNT_MESSAGE = "RENEWAL_AMOUNT"
RENEWAL_REMINDER_MESSAGE = "RENEWAL_REMINDER"
PRINT_RENEWAL_DETAILS = "PRINT_RENEWAL_DETAILS"

INPUT_COMMANDS = {
    "START_SUBSCRIPTION": "process_start_subscription",
    "ADD_SUBSCRIPTION": "process_add_subscription",
    "ADD_TOPUP": "process_add_topup",
    "PRINT_RENEWAL_DETAILS": "process_print_renewal_details",
}
