# errorcodes used in overall application
class ErrorCodes:
    INVALID_DATE = "INVALID_DATE"
    SUBSCRIPTIONS_NOT_FOUND = "SUBSCRIPTIONS_NOT_FOUND"
    DUPLICATE_CATEGORY = "DUPLICATE_CATEGORY"
    DUPLICATE_TOPUP = "DUPLICATE_TOPUP"
    DUPLICATE_PLAN = "DUPLICATE_PLAN"
    INVALID_PLAN_TYPE = "INVALID_PLAN_TYPE"
    INVALID_CATEGORY = "INVALID_CATEGORY"
    INVALID_TOPUP_TYPE = "INVALID_TOPUP_TYPE"
    TOPUP_NOT_FOUND = "TOPUP_NOT_FOUND"
    ADD_SUBSCRIPTION_FAILED = "ADD_SUBSCRIPTION_FAILED"
    ADD_TOPUP_FAILED = "ADD_TOPUP_FAILED"
    INVALID_TOPUP_DURATION = "INVALID_TOPUP_DURATION"
    INVALID_PLAN_DETAILS_MAPPING = (
        "Invalid plan details mapping for the given category and plan type"
    )
    INVALID_INPUT = "INVALID_INPUT"
    USER_ERROR_MSG = "User has no method"
    INVALID_DATE_EXCEPTION_MESSAGE = "ADD_SUBSCRIPTION_FAILED INVALID_DATE"
    INVALID_CATEGORY_EXCEPTION_MESSAGE = "ADD_SUBSCRIPTION_FAILED INVALID_CATEGORY"
    DUPLICATE_CATEGORY_EXCEPTION_MESSAGE = "ADD_SUBSCRIPTION_FAILED DUPLICATE_CATEGORY"
    INVALID_PLAN_TYPE_EXCEPTION_MESSAGE = "ADD_SUBSCRIPTION_FAILED INVALID_PLAN_TYPE"
    DUPLICATE_TOPUP_ERROR_MESSAGE = "ADD_TOPUP_FAILED DUPLICATE_TOPUP"
    INVALID_TOPUP_TYPE_ERROR_MESSAGE = "ADD_TOPUP_FAILED INVALID_TOPUP_TYPE"
    INVALID_TOPUP_DURATION_ERROR_MESSAGE = "ADD_TOPUP_FAILED INVALID_TOPUP_DURATION"
    INVALID_TOPUP_DATE_MESSAGE = "ADD_TOPUP_FAILED INVALID_DATE"
    ADD_TOPUP_FAILED_SUBSCRIPTIONS_NOT_FOUND_MESSAGE = (
        "ADD_TOPUP_FAILED SUBSCRIPTIONS_NOT_FOUND"
    )
    PRINT_RENEWAL_DETAILS_SUBSCRIPTIONS_NOT_FOUND_MESSAGE = "SUBSCRIPTIONS_NOT_FOUND"
