# errorcodes used in overall application
class ErrorCodes:
    INVALID_DATE = "INVALID_DATE"
    SUBSCRIPTIONS_NOT_FOUND = "SUBSCRIPTIONS_NOT_FOUND"
    DUPLICATE_CATEGORY = "DUPLICATE_CATEGORY"
    DUPLICATE_TOPUP = "DUPLICATE_TOPUP"
    DUPLICATE_PLAN = "DUPLICATE_PLAN"
    INVALID_PLAN_TYPE = "INVALID_PLAN_TYPE"
    INVALID_CATEGORY = "INVALID_CATEGORY"
    INVALID_TOPUP_TYPE = "INVALID_TOPUP_TYPE"
    TOPUP_NOT_FOUND = "TOPUP_NOT_FOUND"
    ADD_SUBSCRIPTION_FAILED = "ADD_SUBSCRIPTION_FAILED"
    ADD_TOPUP_FAILED = "ADD_TOPUP_FAILED"
    INVALID_TOPUP_DURATION = "INVALID_TOPUP_DURATION"
    INVALID_PLAN_DETAILS_MAPPING = (
        "Invalid plan details mapping for the given category and plan type"
    )
    INVALID_INPUT = "INVALID_INPUT"
    ADD_SUBSCRIPTION_FAILED = "ADD_SUBSCRIPTION_FAILED"
